### ISSUE TITLE
Tasks for initial release

### ISSUE THREAD

**Issue by keddelzz** [zen-pie/macrowave#18]
- [ ] Specify grammar syntax and DSL
  - [x] #1 Separate specification for scanner and parser or combined one?
  - [ ] #2 Use macro annotations or def macros? (The decision will implicitly shape the syntax)
  - [x] #4 Define syntax of the grammar specification (PR: #7)
  - [x] Create AST for internal representation (PR: #11)
- [x] Read grammar and DSL to internal representation
  - [x] Transform and collect regular expressions and tokens to `scanner.Rule`s (PR: #16)
    - [x] Parser for regular expressions (PR: #17)
  - [x] #20 Find optional whiteSpace token (PR: #21)
  - [x] Transform and collect rules to `parser.Rule`s (PR: #19)
  - [x] Find required start rule (PR: #19)
  - [x] #23 Validate `parser.Rule`s: (Error on useless and unreachable rules) (PR: #32)
  - [x] #22 Extract auxiliary definitions to put them back into the parser class (PR: #25)
- [x] #52 Add mechanism for lifting data (PR: #54)
- [ ] Scanner
  - [x] #27 Construct DFA directly from regular expression (`scanner.Rule`) (PR: #63)
  - [x] #28 Minimize DFA (PR: #63)
  - [x] #29 Build (scanner-) table (PR: #63)
  - [x] #56 (Scanner-) Table compression (PR: #57, #63)
  - [ ] #36 Create (scanner-) driver
- [ ] Parser
  - [x] Preprocessing
    - [x] #37 Calculate First- and Follow-Sets, as well as Nullables (PR: #61)
    - [x] Normalize grammar (PR: #59)
      - [x] #38 Transform regular operations to equivalent productions (PR: #59)
      - [x] #39 Rewrite nested transformations (`^^`) to use synthetic rules (PR: #59)
  - [ ] #40 Construct LR(0)-automaton
  - [ ] #41 Construct LALR(1)-automaton using DeRemer and Penellos Algorithm
  - [ ] #42 Build (parser-) table
  - [ ] #43 Handle user actions in parser (They won't be handled until this point, this leads to a simplification during the construction of the LALR(1)-automaton)
  - [ ] #60 Add synthetic actions during normalization
  - [ ] #44 Create (parser-) driver
- [ ] Test everything (Unit-Test / Integration-Test)
- [ ] Prepare code for initial release
  - [ ] Code cleanup
- [ ] Release initial version
